use strict;
use warnings;
use File::Path qw(remove_tree);
use File::Copy;
use File::Basename;

# load a Rust environment or compile pipeline Rust executables (for developers)

use vars qw($launcherDir $environmentsDir $config %optionArrays %workingSuiteVersions
            $pipelineSuite $pipelineName $pipelineSuiteDir $pipelineDir $suiteBinDir);

#------------------------------------------------------------------------------
# create a versioned Rust development environment
#------------------------------------------------------------------------------
sub createRustEnvironment {
    my ($rustVersion) = @_;
    my $cnd = getRustEnvironmentPaths($rustVersion);

    # check for the existence of the environment; create it if missing
    if ( -f $$cnd{showFile} ) {
        print "Rust environment already exists at $$cnd{dir}\n";
        system("cat $$cnd{showFile}");
    } else {
        open my $outH, ">", $$cnd{initFile} or throwError("could not write to $$cnd{initFile}: $!");
        print $outH "# created by rudi-pipelines-framework/pipeline/launcher/rust.pl\n";
        print $outH "---\n";
        print $outH "channels:\n";
        print $outH "  - conda-forge\n";
        print $outH "dependencies:\n";
        print $outH "  - rust=$rustVersion\n"; # rustc and cargo
        print $outH "  - rust-src=$rustVersion\n";
        close $outH;
        my $bash = "bash -c '
$$cnd{shell_hook}
$$cnd{micromamba} env create --prefix $$cnd{dir} --file $$cnd{initFile} --yes
'";
        print "executing command sequence: $bash\n";
        if(system($bash)){
            remove_tree $$cnd{dir};
            unlink $$cnd{initFile}; 
            throwError("failed to create the rust build environment\n");
        }
        move($$cnd{initFile}, $$cnd{showFile});
    }
    releaseRudiGitLock();
}

#------------------------------------------------------------------------------
# execute a command in the Rust development environment
#------------------------------------------------------------------------------
sub execRustEnvironment {
    my ($rustVersion, @args) = @_;
    my $cnd = getRustEnvironmentPaths($rustVersion);

    # check for the existence of the environment
    -f $$cnd{showFile} or throwError(
        "Rust build environment does not exist at:\n".
        "    $$cnd{dir}\n".
        "Please create it with:\n".
        "    rudi $pipelineName rust --create $rustVersion\n"
    );

    # load the environment
    my $scriptFile = glob("~/.rudi.shellFile");
    my $script = join("\n",
        "rm -f $scriptFile", # the script file deletes itself
        $$cnd{shell_hook},
        "micromamba deactivate", 
        "micromamba activate $$cnd{dir}"
    )."\n";
    $script .= "exec ".join(" ", @args)."\n";
    $script =~ s/\r//g;
    my $shellCommand = "bash $scriptFile";
    open my $outH, ">", $scriptFile or throwError("could not write to $scriptFile: $!");
    print $outH $script; 
    close $outH;
    releaseRudiGitLock();
    exec $shellCommand;
}

#------------------------------------------------------------------------------
# generate rust-analyzer startup script for VSCode integration
#------------------------------------------------------------------------------
sub generateRustAnalyzerScript {
    my ($rustVersion, $gccLoadCommand) = @_;
    my $cnd = getRustEnvironmentPaths($rustVersion);

    # initalize the bash script
    my $scriptFile = "$ENV{HOME}/rust-setup.sh";
    open my $outH, ">", $scriptFile or throwError("could not write to $scriptFile: $!");
    print $outH "#!/bin/bash\n";
    print $outH "\n# generated by rudi-pipelines-framework/pipeline/launcher/rust.pl\n";
    print $outH "\n# creates a rust-analyzer launch wrapper for versioned Rust environments in VS Code\n";
    print $outH "\n# override system rust commands to the versioned environment\n";
    print $outH "export PATH=$$cnd{dir}/bin:\$PATH\n";
    if ($gccLoadCommand) { # load GCC environment for Rust C compilation
        print $outH "\n# load GCC environment for Rust C compilation\n";
        print $outH "$gccLoadCommand\n";
    }
    print $outH "\n# find and execute the call to VS Code rust-analyzer extension\n";
    print $outH "RUST_ANALYZER_DIR=`ls -1dr /\$HOME/.vscode-server/extensions/rust-lang.rust-analyzer* | head -n 1`\n";
    print $outH "RUST_ANALYZER=`echo \"\$RUST_ANALYZER_DIR/server/rust-analyzer\"`\n";
    print $outH "exec \$RUST_ANALYZER \"\$@\"\n"; 
    close $outH;
    chmod 0755, $scriptFile or throwError("could not set execute permissions on $scriptFile: $!");
    print "generated rust-analyzer startup script for VSCode at:\n    $scriptFile\n\n";
    system("cat $scriptFile");
    releaseRudiGitLock();
}

#------------------------------------------------------------------------------
# compile Rust crates listed as crate root directories in 'pipelines/$pipelineName/rust.txt'
# executable targets are copied into directory '$RUDI_DIR/bin/<pipeline_suite>/<pipeline_name>/<target_name>'
#------------------------------------------------------------------------------
sub compileRustExecutables {
    my ($rustVersion, $gccLoadCommand, $noConda) = @_;

    # initalize the bash script
    my $script;
    if (!$noConda){
        my $cnd = getRustEnvironmentPaths($rustVersion);
        -f $$cnd{showFile} or throwError(
            "Rust build environment does not exist at:\n".
            "    $$cnd{dir}\n".
            "Please create it with:\n".
            "    rudi $pipelineName rust --create $rustVersion\n"
        );
        $script = join("\n",
            $$cnd{shell_hook},
            "micromamba deactivate", 
            "micromamba activate $$cnd{dir}"
        )."\n";
    }
    $script .= join("\n",
        # use the --gcc option to load a GCC environment for C linking
        $gccLoadCommand ? $gccLoadCommand : "", 
        "unset RUSTFLAGS",
        # ensure system gcc is used for C linking to avoid conda gcc issues
        # build for x86-64-v3 architecture for modern CPU optimization with high portability
        # do not strip debuginfo since locally compiled binaries are usually used for development
        "export RUSTFLAGS=\"-C linker=gcc -C target-cpu=x86-64-v3\"" 
    )."\n";

    # set binary type based on version and developer-mode
    my $binaryVersion = $ENV{DEVELOPER_MODE} ?  "dev" : $workingSuiteVersions{$pipelineSuiteDir};

    # iterate through each Rust crate defined for the tool suite containing the index pipeline
    my $rustFile = "$pipelineSuiteDir/rust.txt";
    -f $rustFile or throwError("no Rust crate definitions found for suite '$pipelineSuite' at:\n    $rustFile");
    open my $inH, "<", $rustFile or throwError("could not read $rustFile: $!");
    while (my $cratePath = <$inH>) {
        chomp $cratePath;
        $cratePath =~ s/#.*$//; # remove comments
        $cratePath =~ s/^\s+|\s+$//g; # trim whitespace
        next if !$cratePath; # skip blank lines
        my $targetName = basename($cratePath);
        my $binaryPath = "$suiteBinDir/$binaryVersion/$targetName";
        my $script = $script;
        $script .= "\ncd $pipelineSuiteDir/$cratePath\n"; # crate paths are relative to pipeline suite directory
        $script .= "cargo build --release --bin $targetName\n";
        $script .= "mkdir -p $suiteBinDir/$binaryVersion\n";
        $script .= "cp -f target/release/$targetName $binaryPath\n";
        my $bash = "bash -c '\n$script\n'";
        print "executing command sequence: $bash\n";
        if(system($bash)){
            throwError("rust compile failed for crate at:\n    $pipelineSuiteDir/$cratePath\n");
        }
    }
    close $inH;
    releaseRudiGitLock();
}

#------------------------------------------------------------------------------
# shared rust support
#------------------------------------------------------------------------------
sub getRustEnvironmentPaths {
    my ($rustVersion) = @_;
    my ($envName, $envType) = ("rust-$rustVersion", "named");
    getEnvironmentPaths(undef, undef, $envName, $envType);
}

1;
